version: '3.8'

services:
  # Serviço do banco de dados PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: policia-db-compose
    restart: always
    environment:
      # As variáveis são lidas do arquivo .env na mesma pasta
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # Mapeia a porta do host (lida do .env) para a porta do container (fixa)
      - "${DB_PORT}:5432"
    volumes:
      # Persiste os dados do banco na pasta 'pgdata' no host
      - pgdata:/var/lib/postgresql/data

# Define o volume nomeado para persistência dos dados
volumes:
  pgdata: