version: '3.8'

services:
  api:
    build: .
    container_name: policia_api_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres-db
    environment:
      NODE_ENV: development

  postgres-db:
    image: postgres:13
    container_name: policia_api_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 83782813
      POSTGRES_DB: policia_api
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: